### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by cgarciae** [redstone-dart/redstone.dart#100]
Really happy with the new (social) direction Redstone has taken.

In #98 @kaendfinger proposed the creation of a roadmap and I proposed a (TDD) development model based on defining features first, then creating broken features and broken tests, and leaving the implementation to the community (us).

Where shall we create this roadmap? Shall we call it release and use the Milestone? @luizmineo should really tell us where Redstone is headed, what is missing, etc.
What do you think of my proposal for development? Does anybody know how to use a continuous integration system like travis with Dart?

**Comment by azenla** [comment]
@cgarciae It should probably be in the repository. I'll make one. Also, @luizmineo uses drone.io for redstone already. Personally, I would like to move to Travis for simplicity. I'll file another issue for this.

**Comment by cgarciae** [comment]
@redstone-dart/owners
The roadmap has been created under `roadmaps/v0.6.md`. Here is the place to design/document the expected features for the `v0.6` release, get updated on what is missing, discussion on the content could be done through issues. @kaendfinger @austincummings I think changes to this document should always be reviewed.

As for the development model, the proposal is this:
-  Should be release/milestone based
-  Features for each release/milestone should be defined in the roadmap
-  Each feature should be implement **broken** first. Might be in the form of a new class with empty methods, new empty methods on an existing class, or an empty branch of code on an existing method. Example

``` dart
class SomeClass
{
    C newMethod(A a, B b)
    {
        throw new UnimplmentedError ();
    }

    D existingMethod (F f, H h, X newParam)
    {
        //Existing code
        ...
        //New Code
        if (someCondition)
        {
            throw new UnimplmentedError ();
        }
        ...
    }
}
```
-  **Empty** test for each feature should be written along with the broken implementation. Example

``` dart
group ("New Feature X", ()
{
    test ("some test", ()
    {
        throw new UnimplementedError ();
    });
});
```
-  Tests should be checked by Travis or equivalent system. (Although I don't if there will be problems with Github since technically at least 1 test should fail until the very end).
