### ISSUE TITLE
Use Travis CI

### ISSUE THREAD

**Issue by azenla** [redstone-dart/redstone.dart#101]
Currently drone.io is setup for redstone. Should we move this to Travis CI?

**Comment by cgarciae** [comment]
I think the reason is that only Drone.io support Dart. Investigated this issue for myself a few week ago. But would hurt checking again.

**Comment by azenla** [comment]
@cgarciae Travis CI does support Dart. http://docs.travis-ci.com/user/languages/dart/

**Comment by cgarciae** [comment]
@kaendfinger Great! I've never setup travis myself. I'll dig into this. It might take some time while I learn. If somebody has experience with travis it might be quicker.

**Comment by Scorpiion** [comment]
What things does Travis CI do better than Drone.io? Just a little curious.

**Comment by azenla** [comment]
Fixed! Sorry if I stole the thunder on this one, I just really like Continuous Integration :)

**Comment by luizmineo** [comment]
Nice! I've disabled the drone.io hooks. Let me know if you need them back.

**Comment by luizmineo** [comment]
By the way, I've noted that redstone_mapper isn't running the client side tests. I've used content_shell with drone.io (although, the support for it seems broken in recent versions), and pub serve during development.

**Comment by azenla** [comment]
@luizmineo Yes, I'm adding that now.
