### ISSUE TITLE
Make list of organization members public

### ISSUE THREAD

**Issue by Scorpiion** [redstone-dart/redstone.dart#107]
As an open source projects I only see benefits with showing the members of the org. If you are a member  you maybe can see it but to the public you can't see anything right now. The project looks more alive I think when you can see the list of members.

For references you could open up these three links in incognito:
- https://github.com/polymer
- https://github.com/dart-lang
- https://github.com/redstone-dart

**Comment by azenla** [comment]
@Scorpiion That's something we should really do. If I had the power to do it to everyone I would, but each member must do it.

@redstone-dart/owners Would you guys agree to this?

**Comment by Scorpiion** [comment]
@kaendfinger ah, I see, I did not think about that. Good idea to ask the others, then people can choose themselves. Can't really think of anything negative with it at all, just positive things.

**Comment by azenla** [comment]
Yep! Some people don't like it, which is odd. I struggle with getting all the people on my DirectCode organization to make theirs public :P

Also, I plan on adding all of @redstone-dart/owners and @redstone-dart/contributors have access to DirectCode repositories.

**Comment by Scorpiion** [comment]
Okay, I agree, it's a little odd, but if someone feels they don't want to, for whatever reason, that's okay too I think. :)

Thanks for adding me to the org @kaendfinger, I have updated my membership to public now. 

Sounds like a nice idea that too.

**Comment by Scorpiion** [comment]
If anyone wonder how to change this, go here:
https://github.com/orgs/redstone-dart/people

And then there is a dropdown next to your name where you can choose "Public" or "Private".

**Comment by cgarciae** [comment]
ᐧ
Thanks Robert. Changed mine to public.

**Comment by Scorpiion** [comment]
:+1:

**Comment by austincummings** [comment]
I think this can be closed now.
