### ISSUE TITLE
Website is dead

### ISSUE THREAD

**Issue by Pacane** [redstone-dart/redstone.dart#108]
.. as the title says.

**Comment by azenla** [comment]
@luizmineo Can you update the cname to point to the new repo?

**Comment by luizmineo** [comment]
The website is a branch of the redstone repository,  which is served by github pages, so you can easily edit it (I think). I'm not in my computer right now, but I can take a look at it later, if you like to.

**Comment by azenla** [comment]
@luizmineo The domain itself is probably CNAME'd to your own github.io domain. I think that's the issue.

**Comment by luizmineo** [comment]
You are right, I've updated it to redstone-dart.github.io, now I'm not sure if it's is needed to update the organization config on github pages

**Comment by azenla** [comment]
It should be good, thanks @luizmineo :)

**Comment by luizmineo** [comment]
The website is back online

**Comment by OzzieOrca** [comment]
This can be closed
