### ISSUE TITLE
Is it possible to set up virtual hosts in Redstone?

### ISSUE THREAD

**Issue by sonoranDesert** [redstone-dart/redstone.dart#117]
Like how the http_server package does:

http://stackoverflow.com/a/21087254/607036

**Comment by azenla** [comment]
Not quite yet, but I will look into this ASAP.

**Comment by cgarciae** [comment]
`app.start` returns an `HttpServer` so I am guessing this will work

``` dart
void main() async {
  var server = await app.start (port: 8080);
  final virtualServer = new VirtualHost(server);
  final domain1Stream = virtualServer.addHost('domain1.com');
  new VirtualDirectory('/var/www/domain1').serve(domain1Stream);
}
```

**Comment by sonoranDesert** [comment]
Thanks for the quick responses.

@cgarciae In my case I get a "Bad state: Stream was already listened to" error when trying to do that, but I'll dig into that idea some more.

**Comment by cgarciae** [comment]
@sonoranDesert You can try this approach, should work

``` dart
  app.setupConsoleLog();
  app.setUp();

  HttpServer server = await HttpServer.bind('localhost', 7070);
  final virtualServer = new VirtualHost(server);
  final domain1Stream = virtualServer.addHost('domain1.com');

  domain1Stream.listen(app.handleRequest);
```

**Comment by cgarciae** [comment]
I'll close this since @sonoranDesert failed to verify the answer.
