### ISSUE TITLE
Plugins not working within Groups in v0.6

### ISSUE THREAD

**Issue by cgarciae** [redstone-dart/redstone.dart#122]
For test purposes I have this class

``` dart
class User {
  @Field() String name;
}
```

and this test route which decoded to JSON in `v0.5` but fails to decode in `v0.6`

``` dart
@app.Group ('/test')
class TT {

  @app.Route('/test')
  @Encode()
  testTest() async {
    return new User()
      ..name = "Cristian";
  }
}
```

If you extract the method `testTest` from the `Group` as a top level function

``` dart
@app.Route('/test')
@Encode()
testTest() async {
  return new User()
    ..name = "Cristian";
}
```

it works ok. @luizmineo any hints on this?

**Comment by luizmineo** [comment]
It seems a bug in the Processor class, which implements the Manager interface. More specifically, take a look at [this method](https://github.com/redstone-dart/redstone/blob/v0.6/lib/src/processor.dart#L232)

Try to change it to:

``` dart
  List<HandlerMetadata> _getRoutes(dynamic metadata) {
    if (metadata is ApplicationMetadata) {
      return []
        ..addAll(metadata.routes)
        ..addAll(metadata.groups.expand(_getRoutes));
    } else if (metadata is GroupMetadata) {
      return []
        ..addAll(metadata.defaultRoutes)
        ..addAll(metadata.routes);
    }

    return [];
  }
```

I didn't test it myself, so I can't guarantee that this fix the problem.

**Comment by cgarciae** [comment]
@luizmineo thanks! I'll do the change, test and update the repo.

**Comment by cgarciae** [comment]
Worked!
