### ISSUE TITLE
Permissions to upload updates to pub

### ISSUE THREAD

**Issue by cgarciae** [redstone-dart/redstone.dart#132]
I specifically need permissions to upload updates to `redstone_mapper` pub package, but access to all the packages would be nice.

**Comment by azenla** [comment]
Sure!

**Comment by azenla** [comment]
@cgarciae You have been a big help. I have been extremely busy, so it's been hard to keep this project up.

**Comment by Pacane** [comment]
@cgarciae If you still don't have permissions, please reopen an issue.
