### ISSUE TITLE
bool QueryParam not being parsed as a boolean on v0.6 

### ISSUE THREAD

**Issue by cgarciae** [redstone-dart/redstone.dart#133]
This simple examples

``` dart
testQueryParams (@app.QueryParam() bool check) => !check;
```

gives rise to

> type 'String' is not a subtype of type 'bool' of 'check'

meaning that is being passed as a String instead of a bool.

**Comment by luizmineo** [comment]
See [ParametersProcessos.getValueConverter() method](https://github.com/redstone-dart/redstone/blob/v0.6/lib/src/parameters_processor.dart#L179). I think you can just change the last condifition to:

``` dart
if (paramType == boolType) {
  return (String value) => "true" == value.toLowerCase();
}
```

**Comment by cgarciae** [comment]
Thanks @luizmineo ! Code fixed and available on pub :)
