### ISSUE TITLE
Is there a way to use a middleware just for some specific endpoints?

### ISSUE THREAD

**Issue by Pacane** [redstone-dart/redstone.dart#134]
Seems like when I do

``` dart
  app.addShelfMiddleware(someMiddleWare());
  app.start();
```

It is used for all the endpoints. I figured I could wrap my middleWare and check for the request.url to see if it matches XYZ endpoints, but I was wondering if there is/should be a way of doing this with redstone/shelf.

I can see in shelf that there's support for route-specific middleware with

``` dart
myRouter.get('/', (_) => new Response.ok("Hello World"), middleware: logRequests());
```

**Comment by Pacane** [comment]
I guess I could also use the strategy in this post http://redstonedart.org/2014/07/18/authentication-and-authorization/

and make a redstone plugin for it (and annotate my groups/specific endpoints with it)

**Comment by cgarciae** [comment]
@Pacane I think Redstone plugins are just shelf middleware under the hood. I've created a couple of  documented and undocumented plugins for Redstone, what do you need?

**Comment by Pacane** [comment]
I was looking to use shelf_auth package but it was using all the endpoints as its scope.

What I need specifically, is to protect my end points with a session mechanism that's based on a token (jwt)

**Comment by Pacane** [comment]
Plugins seem to be the thing I was looking for. Thanks!
