### ISSUE TITLE
v0.6 Error decoding body form to objects that contain integer fields

### ISSUE THREAD

**Issue by cgarciae** [redstone-dart/redstone.dart#135]
I have this test class and route that tries to parse a form containing a integer value

``` dart
class TestClass {
  @Field() int number;
}

@Group('/test')
class TestRoutes {
  @Route('/int-post-param')
  testIntPostParam(@Decode(from: const[app.FORM]) TestClass test) {
    return test.number += 1;
  }
}
```

But this error arises as a result

```
.TestRoutes.testIntPostParam: Error parsing 'test' parameter: MapperException: TestClass#number: type 'String' is not a subtype of type 'int' of 'value'.
```

It look like its trying to decode a Map to a TestClass but fails because the maps "number" field is a String.

**Comment by cgarciae** [comment]
Looking at the code it seems that `request.body`s values are always Strings.

**Comment by cgarciae** [comment]
@luizmineo I don't have experience with reflection, can you tell me how to make the mapper plugin call a `fromJson(Map map)` constructor before giving up?

**Comment by cgarciae** [comment]
How about this?

``` dart
try {
        return decode(data, paramType);
      } catch (e) {
        try {
          return mirrors.reflectClass(paramType).newInstance(#fromStringMap, [data]).reflectee;
        }
        catch (e2) {
          throw new ErrorResponse(
              400, "$handlerName: Error parsing '$paramName' parameter: $e\n\nError using 'fromJson' constructor: $e2");
        }
      }
```

**Comment by cgarciae** [comment]
It might be nicer if the decoder tried to parse String to int before failing in general.

**Comment by Pacane** [comment]
Is this still relevant? Also, shouldn't this issue be opened on the plugin's repo directly [or is it a bug with redstone specifically?]
