### ISSUE TITLE
v0.6 rollout?

### ISSUE THREAD

**Issue by austincummings** [redstone-dart/redstone.dart#136]
This issue is just to open the discussion for pushing v0.6 as the stable version to pub.

My two questions would be:
- What milestone are we waiting to get to?
- What is currently preventing us from getting there?

**Comment by cgarciae** [comment]
I am using 0.6 on production and see no problems. Vote for pushing it as
stable.

**Comment by austincummings** [comment]
Pushing sounds good to me. I haven't had any problems either.

**Comment by Pacane** [comment]
I vote for pushing as well!

**Comment by azenla** [comment]
:+1:

Who wants to do the honors?

**Comment by Pacane** [comment]
Do we have 0.6 docs ready though?

**Comment by RdeWilde** [comment]
So where is it?

**Comment by Pacane** [comment]
I have converted the whole doc to 0.6. I think we should be ready to release 0.6, I'll do that tonight. Unless someone has any concern with that.

**Comment by RdeWilde** [comment]
Awesome! @Pacane

**Comment by Pacane** [comment]
0.6.1 was released!
