### ISSUE TITLE
dependency issue on redstone 0.6.0

### ISSUE THREAD

**Issue by vimalraj-a** [redstone-dart/redstone.dart#140]
I am getting following error while pub get / pub upgrade

Package di has no versions that match >=3.3.1 <4.0.0 derived from:
redstone 0.6.0+1 depends on version >=3.3.1 <4.0.0

**Comment by Pacane** [comment]
Can you show us the complete pubspec or at least the dependencies section?

**Comment by vimalraj-a** [comment]
name: GISServer
version: 0.0.1
description: GIS API Server 
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  GISCommon:
    path: '../GISCommon'
  redstone: "^0.6.0+1"
dev_dependencies:
  test: '>=0.12.0 <0.13.0'

**Comment by Pacane** [comment]
Are you importing the di package from somewhere else? I suspect from `GISCommon`. If so, what version are you importing?

**Comment by vimalraj-a** [comment]
I am not importing di package from `GISCommon`. But I have `dson: "0.1.7"` which is conflicting with redstone's other dependency.

After removing `dson` from `GISCommon` This is resoved.

Thanks for your support to identify the root cause.
