### ISSUE TITLE
multi import Route not support?

### ISSUE THREAD

**Issue by deepseeksss** [redstone-dart/redstone.dart#168]
main.dart

```
import 'dart:io';
import 'package:redstone/redstone.dart' as app;
import 'routes/user.dart';
import 'routes/verify_code.dart';

main(List<String> args) {
  app.setupConsoleLog();
  app.start(address: "0.0.0.0", port: 3000);
}
```

user.dart

```
import 'package:redstone/redstone.dart' as app;

@app.Route("/user")
User() => "user";
```

verify_code.dart

```
import 'package:redstone/redstone.dart' as app;

@app.Route("/verify_code")
VerifyCode() => "verify_code";
```

only the first import user route valid...

**Comment by Pacane** [comment]
How can it be valid? The method has no body. Also, what are you trying to achieve? I'm not sure

**Comment by deepseeksss** [comment]
sorry. there is something wrong when i copy the code.
i want separate many routes to different files such as modules...

**Comment by platelk** [comment]
Have you tried to put them in a library instead and see if it works ?

**Comment by Pacane** [comment]
If I were you, I would use groups they're made for that.

If you don't want to, you can make a library, and have your routes in
different parts of the library.

**Comment by deepseeksss** [comment]
make them to a library is ok
