### ISSUE TITLE
Documentation: Unittest example not working

### ISSUE THREAD

**Issue by Sgoettschkes** [redstone-dart/redstone.dart#176]
I was trying to get the example for [Unit test](http://redstonedart.org/doc/Unit-test/) working and had several issues:
- The unittest package is used but it is not mentioned anywhere. A short note that this package needs to be installed would be nice
- `import 'package:redstone/mocks.dart';` does not work. It has to be `import 'package:redstone/request_mock.dart';`

I didn't find the source code for the documentation. If it's open source, I'd like to contribute!

**Comment by sestegra** [comment]
The documentation is located on `gh-pages` branch.
https://help.github.com/articles/what-are-github-pages/

The corrected unittest code is following

``` dart
library services;

import 'package:redstone/redstone.dart' as app;

@app.Route("/user/:username")
helloUser(String username) => "hello, $username";
```

``` dart
import 'package:test/test.dart';
import 'package:redstone/redstone.dart' as app;
import 'package:your_package_name/services.dart';

main() {
  // Load handlers in 'services' library
  setUp(() => app.redstoneSetUp([#services]));

  // Remove all loaded handlers
  tearDown(() => app.redstoneTearDown());

  test("hello service", () {
    // Create a mock request
    var req = new app.MockRequest("/user/luiz");
    // Dispatch the request
    return app.dispatch(req).then((resp) {
      // Verify the response
      expect(resp.statusCode, equals(200));
      expect(resp.mockContent, equals("hello, luiz"));
    });
  });
}
```

**Comment by sestegra** [comment]
@Pacane this issue could be closed.

**Comment by Pacane** [comment]
@sestegra did you fix it? If so I'll close the issue. Otherwise, I'll fix it.

**Comment by sestegra** [comment]
@Pacane done with #179

**Comment by Pacane** [comment]
Thanks!
