### ISSUE TITLE
is redstone deprecated?

### ISSUE THREAD

**Issue by iapicca** [redstone-dart/redstone.dart#202]
@luizmineo 
Hi, is redstone actively mantained?
no offense, but it appears to be inactive from 4 years as today

**Comment by Pacane** [comment]
no it's not, it's written in big text in the README

**Comment by iapicca** [comment]
> no it's not, it's written in big text in the README
@Pacane 
according to [readme](https://github.com/redstone-dart/redstone/blob/v0.6/README.md) seems it is 

> # Redstone
> 
> *DEPRECATED: This project is unmaintained for a long time, and is not compatible with Dart 2.x and newer.*

**Comment by Pacane** [comment]
It's not actively maintained. You use 2 different (contradictory) questions, one in the title of your issue, and one in your post.

Just to be clear, Redstone is unmainted and deprecated.
