### ISSUE TITLE
How to respond with an HTML

### ISSUE THREAD

**Issue by cgarciae** [redstone-dart/redstone.dart#48]
Is there an easy way to respond with an HTML file in the `web` folder? I most of the example I see respond `json` or `plain text`, but there must be an easy way to respond the start page.

**Comment by avstudios** [comment]
I'm trying to build Single Page App. The second example from https://github.com/redstone-dart/redstone/wiki/Shelf-Middlewares page works fine so far. I'm not only sure how to serve files from root directory if I use links like /page1, /page2 etc... 

```
web/index.html => http://host.com
web/index.html => http://host.com/page1
web/assets/images/animated.png => http://host.com/page1/assets/images/animated.png
```

I'm guessing I need to write something like the bellow code but I'm not sure what should be in the childPage function body.

``` dart
@app.Route("/.*")
childPage() =>  ?;
```

**Comment by cgarciae** [comment]
Your code above is not needed. The shelf static middlewear will match files from the directory you asigned.

For example, if you set `web` as the parent folder and `index.html` as the default asset, given this folder structure

```
- web
  index.html
  - images
    icon1.png
    icon2.png
```

The route to `icon1.png` is `http://host/images/icon1.png`. Its somewhat intuitive.

**Comment by avstudios** [comment]
@cgarciae maybe I was not clear enough. I set 'web' as root folder and when I type in the browser: 

```
http://host.com
```

index.html and all assets are loaded and displayed correctly. This is my home page.

I have also have few subpages like page1, page2, etc.. and when I type:

```
http://host.com/page1
```

I also would like to load index.html  and the assets from root folder. On the client side I'm using route_hierarchical lib so I can display a content for page1 in index.html

At the moment I see only error page with bellow text

```
404 - NOT FOUND
Resource: /page1
```

I hope this explains better what I want to achieve.
