### ISSUE TITLE
Create v0.5 branch and move v0.6 to master

### ISSUE THREAD

**Issue by azenla** [redstone-dart/redstone.dart#99]
Should we move the master branch to v0.5 and move v0.6 to master?

**Comment by azenla** [comment]
cc @cgarciae @austincummings

**Comment by cgarciae** [comment]
@kaendfinger I don't know, will this affect people that have bugs for the current stable version? Will this affect people on pub? I think we should have the master be the latest stable version.

**Comment by austincummings** [comment]
I agree with @cgarciae, we need to ensure that v0.6 is absolutely stable and will not introduce new bugs. I don't think any of us want our code to suddenly be broken when we go in to work on Monday.

**Comment by austincummings** [comment]
We should also resolve all current issues in the issue tracker before we move forward.

**Comment by azenla** [comment]
Ok. Sound sgood :)

**Comment by azenla** [comment]
I opted for a bit different thing. we have 2 branches: v0.6 and v0.5. No master. v0.5 will be the default branch.

**Comment by cgarciae** [comment]
@kaendfinger Is no master possible? Sounds taboo! I think its culturally accepted that the master is what works and that other branches are things in development. It might confuse people. Then again, its just a name. I think more people should look into this.

**Comment by azenla** [comment]
@cgarciae Yes, projects do this sometimes. Such as https://github.com/dart-lang/test, which has a stable branch instead of master.
